#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))

require 'compare_linker'
require 'optparse'
require 'nokogiri'
require 'open-uri'

def get_changelog_link(url, file_name_regexps)
  changelog_markdown_link = ""

  begin
    doc = OpenURI.open_uri(url) do |f|
      charset = f.charset
      html = f.read
      Nokogiri::HTML.parse(html, nil, charset)
    end

    doc.xpath('//div[@class="file-info"]').each do |node|
      file_title = node.xpath("a")
      file_href = node.xpath("a/@href")

      if file_name_regexps.any? { |file_name_regexp| file_name_regexp.match?(file_title.text) }
        changelog_markdown_link << "[#{file_title.text}](#{url}#{file_href.text}) "
      end
    end
  rescue => e
    # puts e
  end

  changelog_markdown_link
end


options = {}

OptionParser.new {|opts|
  opts.banner = 'Usage: bundle exec ruby ./exe/gemfile_updater_tool [options]'

  opts.on('-p', '--pull-request ID', 'Pull Request ID') do |id|
    options[:pull_request] = id.to_i
  end

  opts.on('-repo', '--repository pixiv/factory', 'Repository pixiv/factory') do |v|
    options[:repository] = v
  end
}.parse!

compare_links = CompareLinker.new(options[:repository], options[:pull_request]).make_compare_links

# Markdown table output
puts ""
puts "| gem | diff | check | memo |"
puts "| --- | --- | --- | --- |"

compare_links.each do |compare_link|
  compare_info = /^(.+):\s(.+)/.match(compare_link)

  gem_name = compare_info[1]
  link = compare_info[2]

  file_name_regexps = [/CHANGE/i,/RELEASE/i,/NEWS/i]
  memo_changelog = get_changelog_link(link, file_name_regexps) if link

  puts "| #{gem_name} | [compare](#{link}) | :sun_with_face: | #{memo_changelog} |"
end

puts ""
